agenceVoyageSymfo/PROD/src/Entity/Voyage.php
<?php

namespace App\Entity;

use App\Repository\VoyageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[UniqueEntity(fields: ['nom_voyage'], message: "Ce nom est déjà utilisé")]
#[ORM\Entity(repositoryClass: VoyageRepository::class)]
class Voyage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups('api_voyage_index')]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: "Le nom est obligatoire")]
    #[Assert\Length(min: 4, max: 50, minMessage: "Le nom doit comporter plus de 4 caractères.", maxMessage: "Le nom du voyage ne peut pas avoir plus de 50 caractères.")]
    #[Groups([
        'api_voyage_show',
        'api_voyage_index',
    ])]
    private ?string $nom_voyage = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Url(message: "l'image ne peux pas etre prise en compte")]
    #[Groups([
        'api_voyage_show',
        'api_voyage_index'
    ])]
    private ?string $photo_voyage = null;

    #[ORM\Column]
    #[Groups([
        'api_voyage_show',
        'api_voyage_index'
    ])]
    private ?int $duree_voyage = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups('api_voyage_index')]
    private ?\DateTimeInterface $dateDepart_voyage = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups('api_voyage_index')]
    private ?\DateTimeInterface $dateRetour_voyage = null;

    #[ORM\Column(nullable: true)]
    private ?bool $visibility_voyage = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['api_voyage_index'])]
    private ?int $prix_voyage = null;

    /**
     * @var Collection<int, Categorie>
     */
    #[ORM\ManyToMany(targetEntity: Categorie::class, inversedBy: 'voyages')]
    #[Groups('api_voyage_index')]
    private Collection $categorie;

    /**
     * @var Collection<int, Destination>
     */
    #[ORM\ManyToMany(targetEntity: Destination::class, inversedBy: 'voyages')]
    #[Groups('api_voyage_index')]
    private Collection $destination;

    /**
     * @var Collection<int, Contact>
     */
    #[ORM\OneToMany(targetEntity: Contact::class, mappedBy: 'voyage')]
    private Collection $contact;



    #[ORM\Column(length: 255, nullable: true)]
    #[Groups('api_voyage_index')]
    private ?string $description_voyage = null;

    #[ORM\ManyToOne(inversedBy: 'voyages')]
    #[Groups('api_voyage_index')]
    private ?Utilisateur $user = null;

  

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
        $this->destination = new ArrayCollection();
        $this->contact = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomVoyage(): ?string
    {
        return $this->nom_voyage;
    }

    public function setNomVoyage(string $nom_voyage): static
    {
        $this->nom_voyage = $nom_voyage;

        return $this;
    }

    public function getPhotoVoyage(): ?string
    {
        return $this->photo_voyage;
    }

    public function setPhotoVoyage(string $photo_voyage): static
    {
        $this->photo_voyage = $photo_voyage;

        return $this;
    }

    public function getDureeVoyage(): ?int
    {
        return $this->duree_voyage;
    }

    public function setDureeVoyage(int $duree_voyage): static
    {
        $this->duree_voyage = $duree_voyage;

        return $this;
    }

    public function getDateDepartVoyage(): ?\DateTimeInterface
    {
        return $this->dateDepart_voyage;
    }

    public function setDateDepartVoyage(?\DateTimeInterface $dateDepart_voyage): static
    {
        $this->dateDepart_voyage = $dateDepart_voyage;

        return $this;
    }

    public function getDateRetourVoyage(): ?\DateTimeInterface
    {
        return $this->dateRetour_voyage;
    }

    public function setDateRetourVoyage(?\DateTimeInterface $dateRetour_voyage): static
    {
        $this->dateRetour_voyage = $dateRetour_voyage;

        return $this;
    }

    public function isVisibilityVoyage(): ?bool
    {
        return $this->visibility_voyage;
    }

    public function setVisibilityVoyage(?bool $visibility_voyage): static
    {
        $this->visibility_voyage = $visibility_voyage;

        return $this;
    }

    public function getPrixVoyage(): ?int
    {
        return $this->prix_voyage;
    }

    public function setPrixVoyage(?int $prix_voyage): static
    {
        $this->prix_voyage = $prix_voyage;

        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): static
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie->add($categorie);
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): static
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection<int, Destination>
     */
    public function getDestination(): Collection
    {
        return $this->destination;
    }

    public function addDestination(Destination $destination): static
    {
        if (!$this->destination->contains($destination)) {
            $this->destination->add($destination);
        }

        return $this;
    }

    public function removeDestination(Destination $destination): static
    {
        $this->destination->removeElement($destination);

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContact(): Collection
    {
        return $this->contact;
    }

    public function addContact(Contact $contact): static
    {
        if (!$this->contact->contains($contact)) {
            $this->contact->add($contact);
            $contact->setVoyage($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): static
    {
        if ($this->contact->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getVoyage() === $this) {
                $contact->setVoyage(null);
            }
        }

        return $this;
    }



    public function getDescriptionVoyage(): ?string
    {
        return $this->description_voyage;
    }

    public function setDescriptionVoyage(?string $description_voyage): static
    {
        $this->description_voyage = $description_voyage;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->user;
    }

    public function setUser(?Utilisateur $user): static
    {
        $this->user = $user;

        return $this;
    }


}

agenceVoyageSymfo/PROD/src/Form/VoyageType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Destination;
use App\Entity\Voyage;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoyageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_voyage')
            ->add('destination', EntityType::class, [
                'class' => Destination::class,
                'choice_label' => 'pays',
                'multiple' => true
            ])
            ->add('photo_voyage')
            ->add('duree_voyage')
            ->add('dateDepart_voyage', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('dateRetour_voyage', null, [
                'widget' => 'single_text'
            ])
            ->add('description_voyage')
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class,
                'choice_label' => 'nom_categorie',
                'multiple' => true,
            'expanded' => true,

            ])

            ->add('prix_voyage');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Voyage::class,
        ]);
    }
}

agenceVoyageSymfo/PROD/src/Controller/Api/VoyageController.php
<?php

namespace App\Controller\Api;

use App\Entity\Voyage;
use App\Repository\VoyageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/voyage', name: 'api_voyage_')]
class VoyageController extends AbstractController
{
  #[Route('s', name: 'index')]
  public function index(VoyageRepository $voyageRepo): JsonResponse
  {
    $Voyages = $voyageRepo->findAll();
    return $this->json($Voyages, context: ['groups' => 'api_voyage_index']);
  }

  #[Route('/{id}', name: "show")]
  public function show(Voyage $voyage): JsonResponse
  {
    return $this->json($voyage, context: ['groups' => ['api_voyage_index', 'api_voyage_show']]);
  }
}

agenceVoyageSymfo/PROD/src/Controller/VoyageController.php
<?php

namespace App\Controller;

use App\Entity\Voyage;
use App\Form\VoyageType;
use App\Repository\VoyageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/voyage',name: 'app_voyage_')]
class VoyageController extends AbstractController
{
    #[Route('s', name: 'index', methods: ['GET'])]
    public function index(VoyageRepository $voyageRepository): Response
    {
        return $this->render('voyage/index.html.twig', [
            'voyages' => $voyageRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_USER', message: "Perdu ? ")]
    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $voyage = new Voyage();
        $form = $this->createForm(VoyageType::class, $voyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($voyage);
            $entityManager->flush();

            return $this->redirectToRoute('app_voyage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('voyage/new.html.twig', [
            'voyage' => $voyage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(Voyage $voyage): Response
    {
        return $this->render('voyage/show.html.twig', [
            'voyage' => $voyage,
        ]);
    }

    #[IsGranted('ROLE_USER', message: "Perdu ? ")]
    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Voyage $voyage, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VoyageType::class, $voyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_voyage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('voyage/edit.html.twig', [
            'voyage' => $voyage,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_USER', message: "Perdu ? ")]
    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Voyage $voyage, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voyage->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($voyage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_voyage_index', [], Response::HTTP_SEE_OTHER);
    }
}

agenceVoyageSymfo/PROD/templates/voyage/_delete_form.html.twig
<form method="post" action="{{ path('app_voyage_delete', {'id': voyage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voyage.id) }}">
    <button class="btn">Delete</button>
</form>

agenceVoyageSymfo/PROD/templates/voyage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

agenceVoyageSymfo/PROD/templates/voyage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Voyage{% endblock %}

{% block body %}
    <h1>Edit Voyage</h1>

    {{ include('voyage/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_voyage_index') }}">back to list</a>

    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}

agenceVoyageSymfo/PROD/templates/voyage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage index{% endblock %}

{% block body %}
    <h1>Voyage index</h1>

    <table class="table">
    <style>
    .table { width: 95%}
    </style>
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_voyage</th>
                <th>Photo_voyage</th>
                <th>Duree_voyage</th>
                <th>DateDepart_voyage</th>
                <th>DateRetour_voyage</th>
                <th>Visibility_voyage</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for voyage in voyages %}
            <tr>
                <td>{{ voyage.id }}</td>
                <td>{{ voyage.nomVoyage }}</td>
                <td>{{ voyage.photoVoyage }}</td>
                <td>{{ voyage.dureeVoyage }}</td>
                <td>{{ voyage.dateDepartVoyage ? voyage.dateDepartVoyage|date('Y-m-d') : '' }}</td>
                <td>{{ voyage.dateRetourVoyage ? voyage.dateRetourVoyage|date('Y-m-d') : '' }}</td>
                <td>{{ voyage.visibilityVoyage ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_voyage_show', {'id': voyage.id}) }}">show</a>
                    <a href="{{ path('app_voyage_edit', {'id': voyage.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_voyage_new') }}">Create new</a>
{% endblock %}

agenceVoyageSymfo/PROD/templates/voyage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Voyage{% endblock %}

{% block body %}
    <h1>Create new Voyage</h1>

    {{ include('voyage/_form.html.twig') }}

    <a href="{{ path('app_voyage_index') }}">back to list</a>
{% endblock %}

agenceVoyageSymfo/PROD/templates/voyage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage{% endblock %}

<style></style>
{% block body %}
    <h1>Voyage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ voyage.id }}</td>
            </tr>
            <tr>
                <th>Nom_voyage</th>
                <td>{{ voyage.nomVoyage }}</td>
            </tr>
            <tr>
                <th>Photo_voyage</th>
                <td>{{ voyage.photoVoyage }}</td>
            </tr>
            <tr>
                <th>Duree_voyage</th>
                <td>{{ voyage.dureeVoyage }}</td>
            </tr>
            <tr>
                <th>DateDepart_voyage</th>
                <td>{{ voyage.dateDepartVoyage ? voyage.dateDepartVoyage|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>DateRetour_voyage</th>
                <td>{{ voyage.dateRetourVoyage ? voyage.dateRetourVoyage|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Visibility_voyage</th>
                <td>{{ voyage.visibilityVoyage ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_voyage_index') }}">back to list</a>

    <a href="{{ path('app_voyage_edit', {'id': voyage.id}) }}">edit</a>

    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}