agenceVoyageSymfo/PROD/src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $message_contact = null;

    #[ORM\ManyToOne(inversedBy: 'contact')]
    private ?Voyage $voyage = null;

    #[ORM\ManyToOne(inversedBy: 'contacts')]
    private ?Statut $statut = null;

    #[ORM\ManyToOne(inversedBy: 'contacts')]
    private ?Utilisateur $user = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessageContact(): ?string
    {
        return $this->message_contact;
    }

    public function setMessageContact(?string $message_contact): static
    {
        $this->message_contact = $message_contact;

        return $this;
    }

    public function getVoyage(): ?Voyage
    {
        return $this->voyage;
    }

    public function setVoyage(?Voyage $voyage): static
    {
        $this->voyage = $voyage;

        return $this;
    }

    public function getStatut(): ?Statut
    {
        return $this->statut;
    }

    public function setStatut(?Statut $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->user;
    }

    public function setUser(?Utilisateur $user): static
    {
        $this->user = $user;

        return $this;
    }


}

agenceVoyageSymfo/PROD/src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('user', EntityType::class, [
                'class' => Utilisateur::class,
                'choice_label' =>'nom_utilisateur',
            ])

            ->add('message_contact');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

agenceVoyageSymfo/PROD/src/Controller/Api/ContactController.php
<?php

namespace App\Controller\Api;

use App\Entity\Contact;
use App\Repository\ContactRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/contact', name: 'api_contact_')]
class ContactController extends AbstractController
{
  #[Route('s', name: 'index')]
  public function index(ContactRepository $contactRepo): JsonResponse
  {
    $Contacts = $contactRepo->findAll();
    return $this->json($Contacts, context: ['groups' => 'api_contact_index']);
  }

  #[Route('/{nom}', name: "show")]
  public function show(Contact $contact): JsonResponse
  {
    return $this->json($contact, context: ['groups' => ['api_contact_index', 'api_contact_show']]);
  }
}

agenceVoyageSymfo/PROD/src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ContactRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/contact', name: 'app_contact_')]
class ContactController extends AbstractController
{
    #[Route('s', name: 'index', methods: ['GET'])]
    public function index(ContactRepository $contactRepository): Response
    {
        return $this->render('contact/index.html.twig', [
            'contacts' => $contactRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contact);
            $entityManager->flush();

            return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contact/new.html.twig', [
            'contact' => $contact,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(Contact $contact): Response
    {
        return $this->render('contact/show.html.twig', [
            'contact' => $contact,
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contact $contact, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contact/edit.html.twig', [
            'contact' => $contact,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_USER', message: "Perdu ? ")]

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Contact $contact, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contact->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($contact);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
    }
}

agenceVoyageSymfo/PROD/templates/contact/_delete_form.html.twig
<form method="post" action="{{ path('app_contact_delete', {'id': contact.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
    <button class="btn">Delete</button>
</form>

agenceVoyageSymfo/PROD/templates/contact/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

agenceVoyageSymfo/PROD/templates/contact/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Contact{% endblock %}

{% block body %}
    <h1>Edit Contact</h1>

    {{ include('contact/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contact_index') }}">back to list</a>

    {{ include('contact/_delete_form.html.twig') }}
{% endblock %}

agenceVoyageSymfo/PROD/templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact index{% endblock %}

{% block body %}
    <h1>Contact index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Message_contact</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contact in contacts %}
            <tr>
                <td>{{ contact.id }}</td>
                <td>{{ contact.messageContact }}</td>
                <td>
                    <a href="{{ path('app_contact_show', {'id': contact.id}) }}">show</a>
                    <a href="{{ path('app_contact_edit', {'id': contact.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_contact_new') }}">Create new</a>
{% endblock %}

agenceVoyageSymfo/PROD/templates/contact/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Contact{% endblock %}

{% block body %}
    <h1>Create new Contact</h1>

    {{ include('contact/_form.html.twig') }}

    <a href="{{ path('app_contact_index') }}">back to list</a>
{% endblock %}

agenceVoyageSymfo/PROD/templates/contact/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
    <h1>Contact</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contact.id }}</td>
            </tr>
            <tr>
                <th>Message_contact</th>
                <td>{{ contact.messageContact }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contact_index') }}">back to list</a>

    <a href="{{ path('app_contact_edit', {'id': contact.id}) }}">edit</a>

    {{ include('contact/_delete_form.html.twig') }}
{% endblock %}